enum BreweryType {
  micro
  nano
  regional
  brewpub
  large
  planning
  bar
  contract
  proprietor
  closed
}

type Brewery {
  id: ID!
  name: String!
  breweryType: BreweryType
  address1: String
  address2: String
  address3: String
  city: String
  stateProvince: String
  postalCode: String
  country: String
  longitude: Float
  latitude: Float
  phone: String
  websiteUrl: String
}

type BreweryListResult {
  items: [Brewery!]!
  page: Int!
  perPage: Int!
  hasNextPage: Boolean!
}

type BreweryListMetaResult {
  total: Int!
  page: Int!
  perPage: Int!
  totalPages: Int!
}

input BreweryListFilters {
  byCity: String
  byCountry: String
  byState: String
  byPostal: String
  byType: BreweryType
}

type Query {
  listBreweries(
    page: Int = 1
    perPage: Int = 12
    filters: BreweryListFilters
  ): BreweryListResult!

  listBreweriesMeta(
    page: Int = 1
    perPage: Int = 12
    filters: BreweryListFilters
  ): BreweryListMetaResult!

  searchBreweries(
    query: String!
    page: Int = 1
    perPage: Int = 12
  ): BreweryListResult!

  brewery(id: ID!): Brewery!
}